#!/bin/sh

echo "Running pre-commit hook..."

# Get all staged Go files
STAGED_FILES=$(git diff --cached --name-only --diff-filter=d | grep '\.go$')

if [ -z "$STAGED_FILES" ]; then
    echo "No Go files to format."
    echo "Pre-commit hook completed successfully!"
    exit 0
fi

# Format the files
echo "Formatting Go files..."

for file in $STAGED_FILES; do
    go fmt "$file"
    git add "$file"
done

echo "Pre-commit hook completed successfully!"