name: Deploy to Cloud Run

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  sanitize:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: 'stable'

      - name: Install linting tools
        run: |
          echo "Installing linting tools..."
          go install github.com/golangci/golangci-lint/cmd/golangci-lint@latest
          go install honnef.co/go/tools/cmd/staticcheck@latest
          go install github.com/securego/gosec/v2/cmd/gosec@latest
          echo "$HOME/go/bin" >> $GITHUB_PATH

      - name: Check for unformatted files
        run: |
          echo "Checking for unformatted files..."
          unformatted_files=$(gofmt -l .)
          if [ -n "$unformatted_files" ]; then
            echo "The following files are not formatted correctly:"
            echo "$unformatted_files"
            exit 1
          fi
          echo "All files are formatted correctly."

      - name: Run go vet
        run: |
          echo "Running go vet..."
          go vet ./...

      - name: Run staticcheck
        run: |
          echo "Running staticcheck..."
          staticcheck ./...

      - name: Run gosec
        run: |
          echo "Running gosec..."
          gosec ./...

      - name: Run golangci-lint
        run: |
          echo "Running golangci-lint..."
          golangci-lint run

  test:
    needs: sanitize
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install godotenv
        run: |
          echo "Installing godotenv..."
          go install github.com/joho/godotenv/cmd/godotenv@latest
          echo "Adding Go binary directory to PATH..."
          echo "$HOME/go/bin" >> $GITHUB_PATH

      - name: Run tests
        run: |
          echo "Running tests..."
          make test

  deploy:
    needs: test
    runs-on: ubuntu-latest
    permissions:
      contents: 'read'
      id-token: 'write'
    env:
      IMAGE_ROOT_NAME: "fabiomendeslps/cribe-api"
      GC_SERVICE_NAME: "api-service"

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Get Image Name
        id: image_name
        run: |
          SHA=$(git rev-parse --short HEAD)
          if [[ "${{ github.event_name }}" == "pull_request" ]]; then
            IMAGE_NAME=${{ env.IMAGE_ROOT_NAME }}-staging:$SHA
          else
            IMAGE_NAME=${{ env.IMAGE_ROOT_NAME }}:$SHA
          fi
          echo IMAGE_NAME=$IMAGE_NAME >> $GITHUB_OUTPUT

      - name: Build and Push with Docker Compose
        run: |
          docker compose build
          docker push $IMAGE_NAME
        env:
          IMAGE_NAME: ${{ steps.image_name.outputs.IMAGE_NAME }}

      - name: Cloud SDK Auth
        uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ secrets.GC_CREDENTIALS }}

      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@v2

      - name: Deploy to Cloud Run
        id: deploy
        uses: google-github-actions/deploy-cloudrun@v2
        with:
          service: ${{ github.event_name == 'pull_request' && format('{0}-staging', env.GC_SERVICE_NAME) || env.GC_SERVICE_NAME }}
          region: ${{ secrets.GC_REGION }}
          image: ${{ steps.image_name.outputs.IMAGE_NAME }}
          flags: --allow-unauthenticated

      - name: Log Staging URL
        if: github.event_name == 'pull_request'
        run: |
          echo "Staging deployment URL: ${{ steps.deploy.outputs.url }}"
