name: Deploy to Cloud Run

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: 'read'
      id-token: 'write'
    env:
      IMAGE_ROOT_NAME: "fabiomendeslps/cribe-api"
      GC_SERVICE_NAME: "api-service"

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Get Image Name
        id: image_name
        run: |
          SHA=$(git rev-parse --short HEAD)
          if [[ "${{ github.event_name }}" == "pull_request" ]]; then
            IMAGE_NAME=${{ env.IMAGE_ROOT_NAME }}-staging:$SHA
          else
            IMAGE_NAME=${{ env.IMAGE_ROOT_NAME }}:$SHA
          fi
          echo IMAGE_NAME=$IMAGE_NAME >> $GITHUB_OUTPUT

      - name: Build and Push with Docker Compose
        run: |
          docker compose build
          docker push $IMAGE_NAME
        env:
          IMAGE_NAME: ${{ steps.image_name.outputs.IMAGE_NAME }}

      - name: Cloud SDK Auth
        uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ secrets.GC_CREDENTIALS }}

      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@v2

      - name: Deploy to Cloud Run
        id: deploy
        uses: google-github-actions/deploy-cloudrun@v2
        with:
          service: ${{ github.event_name == 'pull_request' && format('{0}-staging', env.GC_SERVICE_NAME) || env.GC_SERVICE_NAME }}
          region: ${{ secrets.GC_REGION }}
          image: ${{ steps.image_name.outputs.IMAGE_NAME }}
          flags: --allow-unauthenticated

      - name: Log Staging URL
        if: github.event_name == 'pull_request'
        run: |
          echo "Staging deployment URL: ${{ steps.deploy.outputs.url }}"
